---
title: "data_manipulation"
output: github_document
date: "2023-09-22"
---

```{r}
library(tidyverse)
```

Import "FAS_litters.csv" using relative path
```{r}
litters_df = read_csv("./data/FAS_litters.csv")

#turns variable names into snackcase
litters_df = janitor::clean_names(litters_df)
```

Import pups dataset
```{r}
pups_df = read_csv("./data/FAS_pups.csv")

#turns variable names into snackcase
pups_df = janitor::clean_names(pups_df)
```


#to extract only some columns that we need: 'select' fucntion
```{r}
select(litters_df, group, litter_number, gd0_weight)

select(litters_df, group, gd0_weight:gd_of_birth)

select(litters_df, group, starts_with("pups"))

#removes litter_number and keeps everything else
select(litters_df, -litter_number)

select(litters_df, group, -starts_with("gd"))

#rename
select(litters_df, litter_id = litter_number)

#rename and keep everything else
select(litters_df, litter_id = litter_number, everything())

relocate(litters_df, litter_number)
```

`select` vs. `pull`
```{r}
#extracting
select(litters_df, group)

#acts like a vector, has tidyverse logic
pull(litters_df, group)
```

## `filter`

get rid of rows using filter function
```{r}
filter(litters_df, group == "Con7")
filter(litters_df, group == "Mod8")

filter(litters_df, group != "Mod8")

filter(litters_df, gd0_weight > 20)

filter(litters_df, group == "Con7" | group == "Con8")

filter(litters_df, group %in% c("Con7", "Con8"))

```

missing rows
```{r}
#dropping whereever there are missing values
drop_na(litters_df)

#dropping specified columns with missing values
drop_na(litters_df, gd0_weight)
```

## `mutate`
```{r}
mutate(litters_df, wt_gain = gd18_weight - gd0_weight)

mutate(litters_df, group = str_to_lower(group))
```


